{-# LANGUAGE OverloadedStrings #-}

-- Generated by tools/generate-terminal.py from contracts/terminal-item/v1/schema.zt.
module Myque.TerminalFields (terminalFields, historyFields) where

import Data.Aeson.Key (Key)

terminalFields, historyFields :: [Key]
terminalFields = ["schema", "metadata", "history", "evidence", "originalPath"]
historyFields = ["repository", "commit", "path", "digest"]
