#!/usr/bin/env python3
"""Generate Haskell wire-field bindings from the canonical Zutai schema export.
Requires zutai-cli 9026fcf2df919893d82deafc07d0cbde2b75f988 (or the pinned
release toolchain); no host-side Zutai parsing or semantic evaluation.
"""
import json
import pathlib
import subprocess

root = pathlib.Path(__file__).resolve().parents[1]
value = json.loads(subprocess.check_output([
    "zutai-cli", "json", str(root / "contracts/terminal-item/v1/schema.zt")
], text=True))
fields = [field["name"] for field in value["terminal"]["fields"]]
history_fields = [field["name"] for field in value["history"]["fields"]]
source = '''{-# LANGUAGE OverloadedStrings #-}
-- Generated by tools/generate-terminal.py from contracts/terminal-item/v1/schema.zt.
module Myque.TerminalFields (terminalFields, historyFields) where
import Data.Aeson.Key (Key)
terminalFields, historyFields :: [Key]
'''
source += 'terminalFields = ' + json.dumps(fields) + '\n'
source += 'historyFields = ' + json.dumps(history_fields) + '\n'
(root / "src/Myque/TerminalFields.hs").write_text(source)
